### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by masscontrolx** [x31aww/multifon-api#1]
Hmm, not work for me, please see https://imgur.com/jnPyVD5.png

**Comment by x31aww** [comment]
Hi. 
Suppose you haven't got cargo installed. Please look here [rust-install](https://www.rust-lang.org/tools/install).

**Comment by masscontrolx** [comment]
Ок , I`m install rust and cargo..., and not work
https://imgur.com/JMb2z66.png

**Comment by masscontrolx** [comment]
with 
multifon --config 
or 
multifon --login 
onli help see for me)

**Comment by x31aww** [comment]
After rewritten to rust I forgot to reflect example changes. Rust argument parser requires double dash `--` before long arguments.

To use this utility you have to be **megafon** mobile operator user.
1. First of all you need to get SIP password. From your mobile phone send ussd request `*137#` and connect multifon business service. SIP password will arrive in SMS.
2. Now, if you wanna to use config file, you have to change it. Open `./config/multifon.json` in text editor and change `LOGIN` to your mobile number in format `79251234567`, then change `PASSWORD` to password that you got in SMS from step one.
3. `--config` argument requires path to configuration file. It means that if you are inside `multifon-api` folder, where you run `make` to build program, the correct command to get balance will be `multifon --config ./config/multifon.json balance`

If you wanna not to use config you need to use `--login` and `--password`, not only `--login`.
If you don't want every time to write `--config ./path/to/multifon.json` you have to add shell alias. It will depend on your default shell, but for bash you can read example [here](https://shapeshed.com/unix-alias/).

**Comment by masscontrolx** [comment]
hmm, I`m create and edit multifon.json in my home directory and double in .config this file.  not work for me https://imgur.com/Kw5YDcd.png

Please tell me more - is it possible to somehow register a new SIM card via multifon-api without dialing *137# or sms on 1117?

**Comment by x31aww** [comment]
Fixed in `0.1.1`. Please download new version.

This is public api wrapper, it couldn't help you to register. From [multifon](https://multifon.megafon.ru/):
`
набрать USSD-команду *137# ;
отправить любое текстовое SMS на номер 1117 ;
подключение в личном кабинете абонента МегаФон;
подключение через портал МегаФон Бизнес
`

**Comment by masscontrolx** [comment]
Yes, in the eMotion application there was a password in the file:
 (/data/user/0/ru.megalabs.multifon/shared_prefs/LOCAL_PREFERENCES_NAME_FOR_APP.xml in line PREF_SIP_PASSWORD) 
before, you could see it by root, now there is only a token, I know that you can somehow get a password, in addition to the above, so I thought that using multifon-api. Thanks for the detailed answer.

**Comment by masscontrolx** [comment]
hmm error:
mass@gh:~/multifon-api$ multifon --config ./config/multifon.json balance
Error: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "https", host: Some(Domain("sm.megafon.ru")), port: None, path: "/sm/client/balance", query: Some("login=79246******&password=**********"), fragment: None }, source: hyper::Error(Connect, Ssl(Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 336908658, library: "SSL routines", function: "tls12_check_peer_sigalg", reason: "wrong signature type", file: "../ssl/t1_lib.c", line: 1145 }]))) }, X509VerifyResult { code: 0, error: "ok" })) })

**Comment by masscontrolx** [comment]
with:
wget -qO- "https://sm.megafon.ru/sm/client/balance/?login=79246******@multifon.ru&password=**********"
<?xml version="1.0" encoding="UTF-8"?>
<response>
<result>
<code>200</code>
<description>OK</description>
</result>

<balance>58.60</balance>

**Comment by x31aww** [comment]
It is SSL error. To try to help you I need to know what system you are using and what is your SSL version. Paste here output from `uname -a` and `openssl version`.

**Comment by masscontrolx** [comment]
$ uname -a
Linux gh 5.9.0-kali5-amd64 #1 SMP Debian 5.9.15-1kali1 (2020-12-18) x86_64 GNU/Linux

$ openssl version
OpenSSL 1.1.1i  8 Dec 2020

**Comment by x31aww** [comment]
OpenSSL with cipher "DEFAULT@SECLEVEL=2" doesn't work with megafon certs. To fix it you have to:
1. Find openssl dir by running `openssl version -d`
2. Copy from it file `openssl.cnf` to your home folder (rename it to `.openssl_seclevel_1.cnf`)
3. Add to the beginning of that file `openssl_conf = default_conf`
4. Add to the end of that file:
`
[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=1
`

Now you can run multifon with `OPENSSL_CONF=~/.openssl_seclevel_1.cnf multifon --config ~/multifon.json balance`.
Not to write every time `OPENSSL_CONF=~/.openssl_seclevel_1.cnf` you have to create shell alias.

Suppose in some time megafon will update its certs and all this fuckup won't be needed.

**Comment by masscontrolx** [comment]
Is it possible to talk to you in a telegram? Do you speak Russian?

**Comment by masscontrolx** [comment]
telegram @massx
